apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: multi-k8s-jrmv-net-tls
spec:
  secretName: multi-k8s-jrmv-net
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: multi-k8s.jrmv.net
  dnsNames:
    - multi-k8s.jrmv.net
    - www.multi-k8s.jrmv.net
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - multi-k8s.jrmv.net
          - www.multi-k8s.jrmv.net
